INSERT INTO roles (name) VALUES ('CREATE_USER_TYPE');
INSERT INTO roles (name) VALUES ('UPDATE_USER_TYPE');
INSERT INTO roles (name) VALUES ('DELETE_USER_TYPE');
INSERT INTO roles (name) VALUES ('VIEW_USER_TYPE');

INSERT INTO roles (name) VALUES ('VIEW_ROLE');

INSERT INTO roles (name) VALUES ('CREATE_RESTAURANT');
INSERT INTO roles (name) VALUES ('UPDATE_RESTAURANT');
INSERT INTO roles (name) VALUES ('DELETE_RESTAURANT');
INSERT INTO roles (name) VALUES ('VIEW_RESTAURANT');

INSERT INTO roles (name) VALUES ('RESTAURANT_OWNER');

INSERT INTO roles (name) VALUES ('CREATE_USER');
INSERT INTO roles (name) VALUES ('UPDATE_USER');
INSERT INTO roles (name) VALUES ('DELETE_USER');
INSERT INTO roles (name) VALUES ('VIEW_USER');
