spring:
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      data-locations:
        - classpath:db/dev/01_roles.sql
        - classpath:db/dev/02_user_type.sql
        - classpath:db/dev/03_user.sql

  h2:
    console:
      enabled: true
      path: /h2-console          # this is the default anyway
      # settings:                # optional extras
      #   trace: false
      #   web-allow-others: false   # ← keep false unless you really need remote access!
