/* USER TYPE */
INSERT INTO ROLES (NAME) VALUES ('CREATE_USER_TYPE');
INSERT INTO ROLES (NAME) VALUES ('UPDATE_USER_TYPE');
INSERT INTO ROLES (NAME) VALUES ('DELETE_USER_TYPE');
INSERT INTO ROLES (NAME) VALUES ('VIEW_USER_TYPE');

/* ROLE */
INSERT INTO ROLES (NAME) VALUES ('VIEW_ROLE');

/* RESTAURANT */
INSERT INTO ROLES (NAME) VALUES ('CREATE_RESTAURANT');
INSERT INTO ROLES (NAME) VALUES ('UPDATE_RESTAURANT');
INSERT INTO ROLES (NAME) VALUES ('DELETE_RESTAURANT');
INSERT INTO ROLES (NAME) VALUES ('VIEW_RESTAURANT');
