/* USER TYPE */
INSERT INTO ROLES (NAME) VALUES ('CREATE_USER_TYPE');
INSERT INTO ROLES (NAME) VALUES ('UPDATE_USER_TYPE');
INSERT INTO ROLES (NAME) VALUES ('DELETE_USER_TYPE');
INSERT INTO ROLES (NAME) VALUES ('VIEW_USER_TYPE');
